# Breast Cancer cases study

In [1]:
import pandas as pd


In [4]:
pd.__version__

'2.2.3'

In [11]:
#Previsores
X = pd.read_csv('/Users/zan/PycharmProjects/BreastCancerSimples/data/entradas_breast.csv')
X

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

In [13]:
#Classe
y = pd.read_csv('/Users/zan/PycharmProjects/BreastCancerSimples/data/saidas_breast.csv')
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [15]:
import sklearn as sk
from sklearn.model_selection import train_test_split

In [18]:
sk.__version__

'1.5.1'

In [19]:
X_treatment, X_test, y_treatment, y_test = train_test_split(X, y, test_size=0.25)

In [22]:
X_treatment.shape, y_treatment.shape

((426, 30), (426, 1))

In [23]:
X_test.shape, y_test.shape

((143, 30), (143, 1))

In [29]:
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [30]:
tf.__version__

'2.19.0'

In [47]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape=(30,)),
    tf.keras.layers.Dense(units = 16, activation = tf.nn.relu, kernel_initializer = 'random_uniform',),
    tf.keras.layers.Dense(units = 16, activation = tf.nn.relu, kernel_initializer = 'random_uniform',),
    tf.keras.layers.Dense(units = 1, activation  = 'sigmoid')

])

In [48]:
rede_neural.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [56]:
otimizador = tf.keras.optimizers.Adam(learning_rate =  0.001, clipvalue = 0.5)

In [58]:
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy'])

In [59]:
rede_neural.fit(X_treatment, y_treatment, batch_size = 10, epochs = 100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.5279 - loss: 2.6800
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7219 - loss: 0.5124
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7915 - loss: 0.4088 
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - binary_accuracy: 0.7910 - loss: 0.4322
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8247 - loss: 0.3722
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8102 - loss: 0.4734 
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - binary_accuracy: 0.8059 - loss: 0.5294
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8578 - loss: 0.3357 
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 693us/step - binary_accuracy: 0.7803 - loss: 0.4908
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step - binary_accuracy: 0.8309 - loss: 0.4770
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 694us/step - binary_accur

In [63]:
pesos0 = rede_neural.layers[0].get_weights()
pesos0

[array([[ 1.12696856e-01, -1.29655804e-02, -3.46757248e-02,
          8.94383416e-02,  1.10109568e-01,  2.86271825e-04,
         -6.18669212e-01, -2.43364215e-01, -8.23846310e-02,
         -8.97668004e-02,  6.56058490e-02,  3.78518812e-02,
          3.84013876e-02,  3.97915207e-03,  4.11827207e-01,
          1.12375990e-01],
        [-6.37069053e-04, -1.38974980e-01,  2.90610250e-02,
          1.46516010e-01,  7.76099339e-02,  5.54659553e-02,
         -5.04432082e-01, -2.64773220e-01, -2.33607322e-01,
         -5.76471314e-02, -1.26784965e-02,  2.13077441e-02,
         -6.09296188e-02, -8.24937150e-02,  3.99327368e-01,
          1.72130838e-01],
        [ 1.97636336e-02, -1.01302572e-01,  1.05882399e-02,
         -1.87216736e-02, -1.24211676e-01,  1.27445869e-02,
         -2.94326991e-01, -7.13141337e-02,  3.53099294e-02,
         -7.94986787e-04, -7.41995201e-02,  2.24996638e-02,
          3.93687785e-02,  6.48073480e-02,  2.04671547e-01,
          1.62144424e-03],
        [ 1.0057350

In [64]:
len(pesos0)

2

In [65]:
len(pesos0[1])

16

In [68]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1

[array([[-2.45877784e-02,  9.21586622e-03,  7.50782527e-03,
          2.71717496e-02, -1.15768202e-01, -6.46275133e-02,
          5.74052297e-02, -1.14488443e-02, -3.39978151e-02,
         -8.44853371e-02,  2.73534000e-01, -4.26454432e-02,
          3.20932604e-02,  4.35048155e-02, -2.79611144e-02,
          4.73032035e-02],
        [-3.42996269e-02, -1.09350244e-02, -4.61357906e-02,
         -5.11767194e-02, -3.63859609e-02, -8.16836283e-02,
          8.32897518e-03, -1.11557469e-02, -2.18969118e-02,
         -1.09749148e-03, -2.03087926e-02, -7.70593295e-03,
         -4.51031923e-02,  1.17365107e-01, -1.25140622e-01,
          3.51550058e-02],
        [-2.51339320e-02, -3.91992256e-02, -4.12877509e-03,
          2.78212111e-02,  3.55674960e-02, -9.55327600e-03,
         -1.27821509e-02, -3.79893780e-02,  3.89317721e-02,
         -1.64764039e-02, -1.98315866e-02,  2.06555612e-02,
         -2.64449250e-02,  7.75696384e-03, -8.11690092e-03,
         -7.66510237e-03],
        [-1.6506269

In [70]:
pesos2 = rede_neural.layers[2].get_weights()
pesos2

[array([[-0.17473713],
        [ 0.09644452],
        [-0.38639075],
        [-0.31979173],
        [ 0.28012037],
        [-0.5316426 ],
        [-0.7314276 ],
        [-0.25115603],
        [ 0.22963619],
        [ 0.20244366],
        [-0.1558165 ],
        [ 0.16259977],
        [-0.16784419],
        [-0.8392393 ],
        [ 0.25743377],
        [ 0.15068986]], dtype=float32),
 array([0.3903111], dtype=float32)]

In [66]:
pesos0[0]

array([[ 1.12696856e-01, -1.29655804e-02, -3.46757248e-02,
         8.94383416e-02,  1.10109568e-01,  2.86271825e-04,
        -6.18669212e-01, -2.43364215e-01, -8.23846310e-02,
        -8.97668004e-02,  6.56058490e-02,  3.78518812e-02,
         3.84013876e-02,  3.97915207e-03,  4.11827207e-01,
         1.12375990e-01],
       [-6.37069053e-04, -1.38974980e-01,  2.90610250e-02,
         1.46516010e-01,  7.76099339e-02,  5.54659553e-02,
        -5.04432082e-01, -2.64773220e-01, -2.33607322e-01,
        -5.76471314e-02, -1.26784965e-02,  2.13077441e-02,
        -6.09296188e-02, -8.24937150e-02,  3.99327368e-01,
         1.72130838e-01],
       [ 1.97636336e-02, -1.01302572e-01,  1.05882399e-02,
        -1.87216736e-02, -1.24211676e-01,  1.27445869e-02,
        -2.94326991e-01, -7.13141337e-02,  3.53099294e-02,
        -7.94986787e-04, -7.41995201e-02,  2.24996638e-02,
         3.93687785e-02,  6.48073480e-02,  2.04671547e-01,
         1.62144424e-03],
       [ 1.00573506e-02, -2.66274400e

In [39]:
previsoes = rede_neural.predict(X_test)
previsoes = previsoes > 0.5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


In [40]:
previsoes

array([[ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [

In [41]:
y_test

0
187  1
429  1
451  0
215  0
133  1
..  ..
550  1
275  1
450  1
523  1
345  1

[143 rows x 1 columns]

In [42]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [43]:
accuracy_score(y_test, previsoes)

0.8741258741258742

In [44]:
 confusion_matrix(y_test, previsoes)

array([[47,  3],
       [15, 78]])

In [60]:
 rede_neural.evaluate(X_test, y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7107 - loss: 1.3913 


[1.2660560607910156, 0.7272727489471436]